# Generated by Django 5.2.1 on 2025-05-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionlog',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
