# Generated by Django 5.2.1 on 2025-05-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_predictionlog_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionlog',
            name='data',
        ),
    ]
